/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

/**
 *
 * @author Rajveermehra
 */
public class Mtble extends javax.swing.JFrame {

    /**
     * Creates new form Mtble
     */
    public Mtble() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("mess?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        messoffQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Messoff m");
        messoffList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : messoffQuery.getResultList();
        messoffQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Messoff m");
        messoffList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : messoffQuery1.getResultList();
        messoffQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Messoff m");
        messoffList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : messoffQuery2.getResultList();
        messoffQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Messoff m");
        messoffList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : messoffQuery3.getResultList();
        messoffQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Messoff m");
        messoffList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : messoffQuery4.getResultList();
        messoffQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Messoff m");
        messoffList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : messoffQuery5.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, messoffList5, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${accountno}"));
        columnBinding.setColumnName("Accountno");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nostu}"));
        columnBinding.setColumnName("Nostu");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${days}"));
        columnBinding.setColumnName("Days");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${startingDate}"));
        columnBinding.setColumnName("Starting Date");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endingDate}"));
        columnBinding.setColumnName("Ending Date");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mtble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mtble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mtble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mtble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mtble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<myproject.Messoff> messoffList;
    private java.util.List<myproject.Messoff> messoffList1;
    private java.util.List<myproject.Messoff> messoffList2;
    private java.util.List<myproject.Messoff> messoffList3;
    private java.util.List<myproject.Messoff> messoffList4;
    private java.util.List<myproject.Messoff> messoffList5;
    private javax.persistence.Query messoffQuery;
    private javax.persistence.Query messoffQuery1;
    private javax.persistence.Query messoffQuery2;
    private javax.persistence.Query messoffQuery3;
    private javax.persistence.Query messoffQuery4;
    private javax.persistence.Query messoffQuery5;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
